import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

const id = [1, 2, 3, 4, 5];

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <nav>
                    <Link href={`/`}>홈/</Link>
                    <Link href={`/about`}>about/</Link>
                    <Link href={`/contact`}>contact/</Link>
                    {id.map((id) => {
                        return (
                            <Link key={id} href={`/blog/${id}`}>
                                blog{id}/
                            </Link>
                        );
                    })}
                </nav>
                {children}
            </body>
        </html>
    );
}
